### ISSUE TITLE
Unknown table: orderBook25 & No handlers could be found for logger "websocket"

### ISSUE THREAD

**Issue by AshishBaboo** [BitMEX/sample-market-maker#92] opened 2018-04-05 18:05 UTC
HI, i am still getting these two errors.

importing symbol settings for XBTUSD...
Unable to find settings-XBTUSD.py.
2018-04-05 21:42:15,280 - INFO - market_maker - BitMEX Market Maker Version: 1.0

2018-04-05 21:42:15,282 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,orderBook25:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-04-05 21:42:15,282 - INFO - ws_thread - Authenticating with API Key.
2018-04-05 21:42:15,282 - INFO - ws_thread - Started thread
2018-04-05 21:42:17,414 - ERROR - ws_thread - Unknown table: orderBook25
No handlers could be found for logger "websocket"
2018-04-05 21:42:18,315 - ERROR - ws_thread - Couldn't connect to WS! Exiting.

**Comment by ryanfox** [comment] 2018-04-09 16:16
Duplicate of #91 .

**Closed by ryanfox** 2018-04-09 16:16 UTC
